//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbaManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matchup
    {
        public int Id { get; set; }
        public int SeasonId { get; set; }
        public int MatchupTypeId { get; set; }
        public int TeamAwayId { get; set; }
        public int TeamHomeId { get; set; }
        public System.DateTime StartTime { get; set; }
        public int TeamAwayScore { get; set; }
        public int TeamHomeScore { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual MatchupStatu MatchupStatu { get; set; }
        public virtual MatchupType MatchupType { get; set; }
        public virtual Season Season { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
