//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NbaManagement.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Team_Player = new HashSet<Team_Player>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PositionId { get; set; }
        public System.DateTime JoinYear { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string College { get; set; }
        public int CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual PlayerPosition PlayerPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team_Player> Team_Player { get; set; }
    }
}
